In [1]:
import pandas as pd
import numpy as np

### Obtained Dataset from USDA on food access measures in 2010 and 2015
- https://www.ers.usda.gov/data-products/food-access-research-atlas/
- Converted .xlsx file to .csv in Excel

In [2]:
all_data = pd.read_csv("DataDownload2015.csv")

In [3]:
all_data

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga,1,1912,693,0,0,0.000000,0,...,221,1622,217,14,0,14,45,44,26,112
1,1001020200,Alabama,Autauga,1,2170,743,0,181,0.083410,0,...,214,888,1217,5,0,5,55,75,87,202
2,1001020300,Alabama,Autauga,1,3373,1256,0,0,0.000000,0,...,439,2576,647,17,5,11,117,87,108,120
3,1001020400,Alabama,Autauga,1,4386,1722,0,0,0.000000,0,...,904,4086,193,18,4,11,74,85,19,82
4,1001020500,Alabama,Autauga,1,10766,4082,0,181,0.016812,0,...,1126,8666,1437,296,9,48,310,355,198,488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72859,56043000200,Wyoming,Washakie,0,3326,1317,0,57,0.017138,0,...,593,3106,6,15,0,27,172,309,56,116
72860,56043000301,Wyoming,Washakie,1,2665,1154,0,10,0.003752,0,...,399,2377,5,23,0,40,220,446,114,124
72861,56043000302,Wyoming,Washakie,1,2542,1021,0,73,0.028717,0,...,516,2312,11,10,1,26,182,407,82,97
72862,56045951100,Wyoming,Weston,0,3314,1322,0,252,0.076041,0,...,499,3179,15,10,1,47,62,91,108,50
72863,56045951300,Wyoming,Weston,1,3894,1699,0,61,0.015665,0,...,650,3706,6,10,2,44,126,125,95,168

### Split files into Urban/Rural

In [4]:
urban = all_data.loc[all_data["Urban"]==1]
rural = all_data.loc[all_data["Urban"]==0]

### Split data into quarters by each desert range and remove non-relevant columns from each quartered DF

In [9]:
urban_half = urban.iloc[:,np.r_[4:8,13:16,20,31:56]]

In [10]:
urban_one = urban.iloc[:,np.r_[4:8,13:16,21,57:82]]

In [11]:
rural_ten = rural.iloc[:,np.r_[4:8,13:16,22,83:108]]

In [12]:
rural_twenty = rural.iloc[:,np.r_[4:8,13:16,22,109:134]]

In [ ]:
urban_half.to_csv("urban_half.csv")